# Generated by Django 4.1.4 on 2022-12-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
